services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: BazarTPU
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql@17/data

volumes:
  postgres_data: