services:
  db1:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: BazarTPU_ads
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ads_postgres_data:/var/lib/postgresql@17/data
  db2:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: BazarTPU_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql@17/data

volumes:
  ads_postgres_data:
  user_postgres_data: