name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  USER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/user_service
  ADS_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/ads_service
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build User Service
      run: |
        docker build -t chipoh/user_service:latest -f ./user_service/Dockerfile .

    - name: Build Ads Service
      run: |
        docker build -t chipoh/ads_service:latest -f ./ads_service/Dockerfile .

    - name: Push User Service
      run: |
        docker push chipoh/user_service:latest

    - name: Push Ads Service
      run: |
        docker push chipoh/ads_service:latest

    - name: Setup SSH key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/deploy_key
        chmod 600 /home/runner/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts

    - name: Copy docker-compose file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key_path: /home/runner/.ssh/deploy_key
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        source: "docker-compose.yaml"
        target: "/chipoh"
        strip_components: 0

    - name: Deploy to Yandex Cloud
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key_path: /home/runner/.ssh/deploy_key
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: |
          cd /chipoh
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
          docker-compose pull
          docker-compose up -d 